### ISSUE TITLE
Add support for KMS Encryption Context

### ISSUE THREAD

**Issue by flatiron-nick** [Versent/unicreds#35]
Credstash added support for [KMS Encryption Contexts](http://docs.aws.amazon.com/kms/latest/developerguide/encryption-context.html) in [this pull request](https://github.com/fugue/credstash/pull/18). 

Would it be possible to add support for Encryption Contexts in unicreds too?

**Comment by wolfeidau** [comment]
Great suggestion,

I am just read over the blog post detailing how it works.

http://blogs.aws.amazon.com/security/post/Tx2LZ6WBJJANTNW/How-to-Protect-the-Integrity-of-Your-Encrypted-Data-by-Using-AWS-Key-Management

I am most certainly interested in supporting this feature!

Thanks for mentioning it.

**Comment by flatiron-nick** [comment]
Awesome, thanks so much! 👍

**Comment by wolfeidau** [comment]
Added some examples https://github.com/Versent/unicreds#examples I used the existing flags parser.
