### ISSUE TITLE
Avoid adding EOF line-feed

### ISSUE THREAD

**Issue by ColinHebert** [Versent/unicreds#41]
Currently a password without a linefeed gets printed with an extra linefeed from the unicreds tool.

This has been resolved in credstash with the option `-n` (or `--noline`). It helps with binary files and within scripts where the output is expected to be the password (and only that).

**Comment by wolfeidau** [comment]
Great suggestion, I noticed it in credstash when working on some other new features and wondered what the use cases were.

Sounds like you have highlighted one, will add this flag today.
