### ISSUE TITLE
Allow getting a specific version of a secret

### ISSUE THREAD

**Issue by alsmola** [Versent/unicreds#44]
Currently you can only get the latest version of a secret without getting every secret. It would be nice to be able to specify a version in the `GetSecret` function: https://github.com/Versent/unicreds/blob/master/ds.go#L148

**Comment by wolfeidau** [comment]
👍 wanted to wait for someone to need this feature. Will add this in the next few days, need to do a bit of refactoring / tidy up as well.

Cheers

**Comment by alsmola** [comment]
I have a version of this ready to review once my other PR is merged: https://github.com/Clever/unicreds/compare/fix-auto-versioning...Clever:support-get-version

**Comment by wolfeidau** [comment]
@alsmola Even better 👍 🎉

**Comment by wolfeidau** [comment]
@alsmola If you could rebase master now to pick up the mock testing fixes prior to that pull request it would be much appreciated.

Cheers

**Comment by wolfeidau** [comment]
#46 fixes this
