### ISSUE TITLE
Cannot get specific version of credential

### ISSUE THREAD

**Issue by rowanu** [Versent/unicreds#48]
Using 1.4.0 on OSX, I get an error every time I supply a version argument to `get`:

```
$ unicreds list -r ap-southeast-2
+---------+---------+--------------------------------+
|  NAME   | VERSION |           CREATED-AT           |
+---------+---------+--------------------------------+
| testing |       5 | 2016-09-07 10:27:07 +1000 AEST |
+---------+---------+--------------------------------+
$ unicreds get testing 5 -r ap-southeast-2
unicreds: error: unexpected 5, try --help
```

Getting the credential without a version argument works as expected.

**Comment by wolfeidau** [comment]
Heya mate, that feature got added in 1.5.0

https://github.com/Versent/unicreds/releases/tag/v1.5.0

I have updated the homebrew tap to 1.5.0 so you should be able to upgrade!
