### ISSUE TITLE
Add -r --region flag

### ISSUE THREAD

**Issue by wolfeidau** [Versent/unicreds#5]
This is a common option for AWS focused tool so it makes sense to add it. 

cc @romanrev

**Comment by ojongerius** [comment]
`--region` is supported, right? Do you care about '-r'?

**Comment by wolfeidau** [comment]
Yeah I just need to read the documentation for the cobra and adjust the params I believe.

We raised it because we are heavy users of AWS cli and want to where possible match their conventions.

I have a bit of work to do in this area and this is my reminder ticket :)

Cheers

**Comment by ojongerius** [comment]
'--region' and '-r' are supported as of #14. Not sure what other work needs doing for this issue.

**Comment by wolfeidau** [comment]
awesome closing.
