### ISSUE TITLE
Using Unicreds in AWS Lambda

### ISSUE THREAD

**Issue by Siva7891** [Versent/unicreds#58]
Can we use Unicers for the functions that are deployed in AWS Lambda?

**Comment by SonOfBytes** [comment]
I haven't done this with unicreds - that said a lambda function should be able to run an arbitrary command.

This AWS blog may help

https://aws.amazon.com/blogs/compute/running-executables-in-aws-lambda/

**Comment by Siva7891** [comment]
Thanks for pointing out the relevant blog post. I will give it a try.

**Comment by jolexa** [comment]
Yes, it is perfectly fine to use unicreds in a lambda function, one of the nice things about Go executables.. This is not really an applicable GH issue and should be closed.
