### ISSUE TITLE
DAX Support

### ISSUE THREAD

**Issue by bacoboy** [Versent/unicreds#72]
Haven't worked out the pricing yet, but unless you are accessing a ton of secrets all the time, most will provision dynamo with a read and write provisioning of 1 (about $0.59/mo at current pricing).  But I've noticed that I get alarms when multiple secrets are read as a server comes up (and it reads say 8 things) in a very short time.  Now, I don't want to insert sleeps or something dumb like that, but another option MAY be to put a small DAX accelerator in front of these tiny dynamo tables (which are basically R/O and would benefit from a tiny tiny cache).

So making a placeholder issue here to consider a code change to support specifying a DAX endpoint in lieu of a dynamo table name.

Like I said, not sure if the pricing works out, but might be useful for some use cases...

**Comment by bacoboy** [comment]
OK I found the pricing [here](https://d0.awsstatic.com/product-marketing/Amazon%20DynamoDB%20Accelerator%20(DAX)%20Pricing.pdf).  The lowest tier is a pretty steep hourly costs.  So unless you are beating on credstash all the time, I don't see how it would work out in your favor -- but it might.

Leaving open for discussion. If people think there isn't value, then close this issue...

**Comment by wolfeidau** [comment]
Yeah DAX is only supported using a closed source Java client at the moment.

**Comment by bacoboy** [comment]
Seems like the on-demand pricing in AWS is a better solution for this cost wise.  Closing.
