### ISSUE TITLE
Dynamodb AWS SDK SSL/TLS certificates issued by ATS

### ISSUE THREAD

**Issue by alexlance** [Versent/unicreds#79]
Hi there, we recently got an email from AWS suggesting that one of our applications was using dynamodb with a slightly older AWS SDK. We just wanted to check that unicreds used an up-to-date SDK? Here is the meat of the email:
> 
> We recently analyzed your use of DynamoDB. During that process, we noticed you have a system that makes calls to DynamoDB using either an older AWS SDK or an unknown SDK that may not support SSL/TLS certificates issued by Amazon Trust Services (ATS).
> 
> Beginning on May 14, 2018, Amazon DynamoDB will update the SSL/TLS certificates the service uses to secure communications. Once the update is complete, ATS will issue the SSL/TLS certificates used by DynamoDB. ATS is also the certificate authority (CA) used by AWS Certificate Manager.
> 
> After DynamoDB migrates to certificates issued by ATS, applications that use an SDK (i.e., one that does not properly handle the new certificates) may stop working. In order for your application to continue to operate normally, you may need to migrate to a newer AWS SDK, or modify your custom SDK to trust ATS.
> 
> The following documentation provides more information and guides you through the process: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ats-certs.html

**Comment by wolfeidau** [comment]
Gday @alexlance 

Your in luck, I recently did a release to upgrade the SDK to the latest release as at end of February. 

https://github.com/Versent/unicreds/blob/master/Gopkg.toml#L37-L38 is the version i am using.

https://github.com/aws/aws-sdk-go/releases/tag/v1.12.70

Cheers

**Comment by alexlance** [comment]
Hi thank you for the quick reply - just looking a little closer at the article and it looks like Go might not bundle its own certs too.
Cheers, Alex
